config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :streams do
    get '/playlist' => 'streams#playlist'
    get '/current_song' => 'streams#current_song'
  end
  root 'streams#index'

  get "/stream_subscription" => "streams#subscription"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base
  belongs_to :stream
  validates :song, uniqueness: true, unless: :last_song_differs
  after_create :notify

  def notify
    $redis.publish "songs", { song: self }.to_json
  end

  def last_song_differs
    stream.playlist_items.any? &&
      song != stream.playlist_items.last.song
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  has_many :playlist_items
  validates :title, :server, :mount, presence: true
  validates :title, uniqueness: true
  validates :mount, uniqueness: { scope: :server,
                                  message: "should exist once per server" }
  scope :enabled, -> { where(enabled: true) }

  def url_status # returns full url
    self.get_url_status
  end

  def url_play
    self.get_url_play
  end

  def self.sync_playlists
    enabled.map(&:sync_latest_song)
  end

  def sync_latest_song
    require 'open-uri'
    page = open_url(self.get_url_status)
    song = get_current_song(page)
    @song = fix_song_title(song)
    save_song
  end

  protected

  def save_song
    self.playlist_items.create(song: @song)
  end

  def fix_song_title song
    song.gsub('_', ' ').gsub('-', ' - ')
  end

  def get_current_song doc
    doc.xpath('//td[contains(text(),"Current Song")]//following-sibling::td').text
  end

  def open_url url
    Nokogiri::HTML.parse open(url).read
  end

  def get_url_status
    URI.join(self.server, "status.xsl?mount=#{self.mount}").to_s
  end

  def get_url_play
    URI.join(self.server, self.mount).to_s
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  before_create :set_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :async, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:wordpress_hosted]

  def admin?
    self.role && self.role.name == 'admin'
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  private

  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def authenticate_admin
    redirect_to root_path, alert: 'Access Denied' unless current_user && current_user.admin?
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :set_stream,
    only: [:show, :edit, :update, :destroy, :playlist, :current_song]
  before_action :authenticate_admin,
    except: [:show, :index, :playlist, :current_song, :subscription]
  include Tubesock::Hijack

  # GET /streams
  # GET /streams.json
  def index
    @streams = Stream.all
  end

  # GET /streams/1
  # GET /streams/1.json
  def show
  end

  # GET /streams/new
  def new
    @stream = Stream.new
  end

  # GET /streams/1/edit
  def edit
  end

  # POST /streams
  # POST /streams.json
  def create
    @stream = Stream.new(stream_params)

    respond_to do |format|
      if @stream.save
        format.html { redirect_to @stream, notice: 'Stream was successfully created.' }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1
  # PATCH/PUT /streams/1.json
  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to @stream, notice: 'Stream was successfully updated.' }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream.destroy
    respond_to do |format|
      format.html { redirect_to streams_url, notice: 'Stream was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def playlist
    respond_to do |format|
      format.json {
        render json: {
          genre: @stream.title,
          url: @stream.url_play,
          history: @stream.playlist_items.order("created_at DESC")
        }
      }
      format.html { redirect_to @stream }
    end
  end

  def current_song
    item = @stream.playlist_items.last
    respond_to do |format|
      format.json { render json: { song: item.song, created_at: item.created_at } }
      format.html { redirect_to @stream }
    end
  end

  def subscription
    hijack do |sock|
      redis_thread = Thread.new do
        Redis.new.subscribe "songs" do |on|
          on.message do |_channel, song|
            sock.send_data song
          end
        end
      end

      sock.onmessage do |m|
        Redis.new.publish "songs", m
      end

      sock.onclose do
        redis_thread.kill
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stream
    @stream = Stream.find(params[:id] || params[:stream_id])
  end

  # Never trust parameters from the scary internet.
  def stream_params
    params.require(:stream).permit(:title, :server, :mount)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def wordpress_hosted
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Wordpress Hosted"
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.wordpress_hosted_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type.to_sym
    when :success;  'alert-success'
    when :error;    'alert-danger'
    when :alert;    'alert-warning'
    when :notice;   'alert-info'
    else; flash_type.to_s
    end
  end
end

app/views/layouts/_footer.html.slim
footer
  - if current_user && current_user.admin?
    = link_to 'New Stream', new_stream_path
  - else
    = link_to 'Suggest Stream', 'http://goo.gl/forms/C3Jf5tRn5L', target: '_blank'
  = " | "
  = link_to 'Feedback Form', 'http://goo.gl/forms/mAl0qyIQk2', target: '_blank'
  br
  = link_to('Όροι χρήσης', '#') + " -  " + link_to('Βεβαίωση', 'https://ccradio.ellak.gr/media/ccradio-certification.pdf', target: '_blank')+ "  -  Υλοποίηση & συντήρηση από "+link_to('ΕΕΛ/ΛΑΚ', '#')+" με χρήση των Ανοιχτών Λογισμικών #{link_to('Rails', 'http://rubyonrails.org/', target: '_blank')} και #{link_to('Icecast', 'http://www.icecast.org/', target: '_blank')}".html_safe

app/views/layouts/_nav.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand', id: 'refresh-root', refresh: "main-content", onclick: "event.preventDefault(); Page.refresh({url: '#{root_path}', onlyKeys: ['main-content']});" do
        |CC
        span RADIO
    .collapse.navbar-collapse
      / ul.nav.navbar-nav
      ul.nav.navbar-nav.navbar-right
        li
          a href="#"  Contact
        li
          a href="#"  About
        li.dropdown
          a.dropdown-toggle href="#" data-toggle="dropdown"
            span> Account
            span.caret
          ul.dropdown-menu
            = render 'layouts/nav_account'

app/views/layouts/_nav_account.html.slim
- if current_user
  li
    = link_to 'Log Out', destroy_user_session_path, method: :delete
- else
  li
    = link_to 'Log In', user_omniauth_authorize_path(:wordpress_hosted)
  / li
  /   = link_to 'Register', new_user_registration_path

app/views/layouts/_player.html.erb
<div id="jquery_jplayer_1" class="jp-jplayer" style="width: 0px; height: 0px;"><img id="jp_poster_0" style="width: 0px; height: 0px; display: none;">
  <audio id="jp_audio_0" preload="none" src="http://listen.radionomy.com/abc-jazz" title="ABC Jazz"></audio>
</div>
<div id="jp_container_1" class="jp-audio-stream" role="application" aria-label="media player">
  <div class="jp-type-single">
    <div class="jp-gui jp-interface">
      <div class="jp-controls">
        <button class="jp-play" role="button" tabindex="0">play</button>
      </div>
      <div class="jp-volume-controls">
        <button class="jp-mute" role="button" tabindex="0">mute</button>
        <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
        <div class="jp-volume-bar">
          <div class="jp-volume-bar-value" style="width: 80%;"></div>
        </div>
      </div>
    </div>
    <div class="jp-details">
      <div class="jp-title" aria-label="title">ABC Jazz</div>
    </div>
    <div class="jp-no-solution" style="display: none;">
      <span>Update Required</span>
      To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
    </div>
  </div>
</div>

app/views/layouts/application.html.slim
doctype html
html
  head
    title CreativeCommons Radio
    = stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true, async: Rails.env.production?
    = csrf_meta_tags
  body data-action="#{action_name}"
    = render 'layouts/nav'
    .container
      .row refresh-never="" tg-static=""
        .play
          = render 'layouts/player'
      - flash.each do |name, msg|
        div class="alert #{bootstrap_class_for(name)}" = msg
      .row#main-content refresh="main-content"
        = yield
    = render 'layouts/footer'

app/views/streams/_form.html.slim
= form_for stream do |f|
  - if stream.errors.any?
    #error_explanation
      h2 = "#{pluralize(stream.errors.count, "error")} prohibited this stream from being saved:"
      ul
        - stream.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :server
    = f.text_field :server
  .field
    = f.label :mount
    = f.text_field :mount
  .actions = f.submit

app/views/streams/edit.html.slim
h1 Editing stream

== render 'form', :stream => @stream

= link_to 'Show', @stream
'|
= link_to 'Back', streams_path

app/views/streams/index.html.slim
h1 Listing Streams

table.table.table-stripped
  thead
    tr
      th Title
      th Song
      th Play
      - if current_user && current_user.admin?
        th
        th
  tbody
    - @streams.each do |stream|
      tr stream-id="#{stream.id}"
        td.title = link_to stream.title, stream, id: "refresh-stream-#{stream.id}", refresh: "main-content", onclick: "event.preventDefault(); Page.refresh({url: '#{stream_path(stream)}', onlyKeys: ['main-content']});"
        td.song = stream.playlist_items.last.song rescue nil
        td.play = link_to "Play #{stream.title}", '#', class: 'player-link', 'data-title': stream.title, 'data-url': stream.url_play, id: "play-stream-#{stream.id}"
        - if current_user && current_user.admin?
          td = link_to 'Edit', edit_stream_path(stream)
          td = link_to 'Destroy', stream, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/streams/new.html.slim
h1 New stream

== render 'form', :stream => @stream

= link_to 'Back', streams_path

app/views/streams/show.html.slim
p#notice = notice

table.table.table-bordered.station-info data-url="#{stream_current_song_path @stream}" stream-id="#{@stream.id}"
  thead
    tr
      th Genre
      th URl
  tbody
    tr
      td = @stream.title
      td = URI.join(@stream.server, @stream.mount)

- if @stream.playlist_items.any?
  table.table.table-hover.table-stripped.playlist
    thead
      tr
        th Song
        th Date
    tbody
      - @stream.playlist_items.order("created_at DESC").limit(10).each do |song|
        tr
          td = song.song
          td = song.created_at
- else
  .alert.alert-info no playlist history

- if current_user && current_user.admin?
  = link_to 'Edit', edit_stream_path(@stream)
  '|
= link_to 'Back', streams_path, class: "btn btn-primary", id: "refresh-main-content", onclick: "event.preventDefault(); Page.refresh({url: '#{streams_path}', onlyKeys: ['main-content']});", 'full-refresh' => 'true'